version: '3.8'
services:
  nextjs_app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db # Veri tabanını sunucuda saklar
    restart: always
    environment:
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=https://fitcoach.akoroglu.com.tr
      - AUTH_SECRET=uydurma_bir_sey_yaz_buraya